name: CI

on:
  push:

permissions: {}

concurrency:
  group: ${{ github.actor }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  c-build-library:
    name: 🏗️ Build C library
    strategy:
      matrix:
        runs-on:
          - ubuntu-20.04
          - ubuntu-latest
          - macos-latest
          - windows-latest
        compiler:
          - gcc-14
          - clang-19.1.0
        exclude:
          - runs-on: macos-latest
            compiler: clang-19.1.0
          - runs-on: windows-latest
            compiler: clang-19.1.0
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install compiler
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: "3.31.6"
          setup-cpp: false
      - name: 🔧 Configure CMake
        run: cmake -S c/ -B c/build/ -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=${{ env.CC }} -D CMAKE_CXX_COMPILER=${{ env.CXX }} -D BUILD_SHARED_LIBS=NO -D TIREX_TRACKER_BUILD_DOCS=NO -D TIREX_TRACKER_BUILD_DEB=NO -D TIREX_TRACKER_BUILD_EXAMPLES=NO
      - name: 🏗️ Build library
        run: cmake --build c/build/ --config Release --target measure_full
      - name: 📤 Upload Linux library
        if: matrix.runs-on == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: c-library-linux
          path: c/build/extensions/libmeasure_full.so
      - name: 📤 Upload macOS library
        if: matrix.runs-on == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: c-library-macos
          path: c/build/extensions/libmeasure_full.dylib
      - name: 📤 Upload Windows library
        if: matrix.runs-on == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: c-library-windows
          path: c/build/extensions/Release/measure_full.dll
  c-check-format:
    name: 🔍 Check C code format
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install compiler
        uses: aminya/setup-cpp@v1
        with:
          clang-format: "19.1.0"
          setup-cpp: false
      - name: 🔍 Check Codestyle
        working-directory: ${{github.workspace}}/c/
        run: find src/ include/ -type f -iregex '^.*\.\(c\|h\|cpp\|hpp\|cc\|hh\)$' | xargs clang-format-19 --dry-run --Werror --Wno-error=unknown
  c-build-cli:
    name: 🏗️ Build C CLI
    strategy:
      matrix:
        runs-on:
          - ubuntu-20.04
          - ubuntu-latest
          - macos-latest
          - windows-latest
        compiler:
          - gcc-14
          - clang-19.1.0
        exclude:
          - runs-on: macos-latest
            compiler: clang-19.1.0
          - runs-on: windows-latest
            compiler: clang-19.1.0
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install compiler
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: "3.31.6"
          setup-cpp: false
      - name: 🔧 Configure CMake
        run: |
          cmake -S c/ -B c/build/ -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=${{ env.CC }} -D CMAKE_CXX_COMPILER=${{ env.CXX }} -D BUILD_SHARED_LIBS=NO -D TIREX_TRACKER_BUILD_DOCS=NO -D TIREX_TRACKER_BUILD_DEB=NO -D TIREX_TRACKER_BUILD_EXAMPLES=YES
      - name: 🏗️ Build Linux binary
        run: cmake --build c/build/ --config Release --target measure
      - name: 📤 Upload Linux CLI
        if: matrix.runs-on == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: c-cli-linux
          path: c/build/examples/03_measure_command/measure
      - name: 📤 Upload macOS CLI
        if: matrix.runs-on == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: c-cli-macos
          path: c/build/examples/03_measure_command/measure
      - name: 📤 Upload Windows CLI
        if: matrix.runs-on == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: c-cli-windows
          path: c/build/examples/03_measure_command/Release/measure.exe
  c-build-debian-package:
    name: 🏗️ Build Debian package
    strategy:
      matrix:
        configuration:
          - runs-on: ubuntu-latest
            artifact: c/build/tirex-tracker-*-Linux.deb
        compiler:
          - gcc-14
          - clang-19.1.0
    runs-on: ${{ matrix.configuration.runs-on }}
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install compiler
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
      - name: 🔧 Configure CMake
        run: |
          cmake -S c/ -B c/build/ -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=${{ env.CC }} -D CMAKE_CXX_COMPILER=${{ env.CXX }} -D BUILD_SHARED_LIBS=NO -D TIREX_TRACKER_BUILD_DOCS=NO -D TIREX_TRACKER_BUILD_DEB=YES -D TIREX_TRACKER_BUILD_EXAMPLES=NO
      - name: 🏗️ Build Debian package
        run: cmake --build c/build/ --config Release --target package
      - name: 📤 Upload Debian package
        if: matrix.configuration.runs-on == 'ubuntu-latest' && matrix.compiler == 'clang-19.1.0'
        uses: actions/upload-artifact@v4
        with:
          name: c-debian-package
          path: ${{ matrix.configuration.artifact }}
  jvm-build:
    name: 🏗️ Build JVM library
    strategy:
      matrix:
        java: # Java LTS versions
          - "8"
          - "11"
          - "17"
          - "21"
    runs-on: ubuntu-latest
    needs:
      - c-build-library
      - c-check-format
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle
          cache-dependency-path: |
            jvm/example/build.gradle.kts
            jvm/library/build.gradle.kts
      - name: 📥 Download Linux library
        uses: actions/download-artifact@v4
        with:
          name: c-library-linux
          path: jvm/library/src/main/resources/
      - name: 📥 Download macOS library
        uses: actions/download-artifact@v4
        with:
          name: c-library-macos
          path: jvm/library/src/main/resources/
      - name: 📥 Download Windows library
        uses: actions/download-artifact@v4
        with:
          name: c-library-windows
          path: jvm/library/src/main/resources/
      - name: 🏗️ Build project
        run: jvm/gradlew --project-dir jvm/ build
  jvm-test:
    name: 🧪 Test JVM library
    strategy:
      matrix:
        java: # Java LTS versions
          - "8"
          - "11"
          - "17"
          - "21"
    runs-on: ubuntu-latest
    needs:
      - c-build-library
      - c-check-format
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle
          cache-dependency-path: |
            jvm/example/build.gradle.kts
            jvm/library/build.gradle.kts
      - name: 📥 Download Linux library
        uses: actions/download-artifact@v4
        with:
          name: c-library-linux
          path: jvm/library/src/main/resources/
      - name: 📥 Download macOS library
        uses: actions/download-artifact@v4
        with:
          name: c-library-macos
          path: jvm/library/src/main/resources/
      - name: 📥 Download Windows library
        uses: actions/download-artifact@v4
        with:
          name: c-library-windows
          path: jvm/library/src/main/resources/
      - name: 🧪 Test with Gradle
        run: jvm/gradlew --project-dir jvm/ test
  jvm-publish:
    name: 🚀 Publish JVM library to GitHub Packages
    strategy:
      matrix:
        java: # Java LTS versions
          - "8"
          - "11"
          - "17"
          - "21"
    if: github.event_name == 'push' && endsWith(github.event.base_ref, 'master') && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs:
      - c-build-library
      - c-check-format
      - jvm-build
      - jvm-test
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle
          cache-dependency-path: |
            jvm/example/build.gradle.kts
            jvm/library/build.gradle.kts
      - name: 📥 Download Linux library
        uses: actions/download-artifact@v4
        with:
          name: c-library-linux
          path: jvm/library/src/main/resources/
      - name: 📥 Download macOS library
        uses: actions/download-artifact@v4
        with:
          name: c-library-macos
          path: jvm/library/src/main/resources/
      - name: 📥 Download Windows library
        uses: actions/download-artifact@v4
        with:
          name: c-library-windows
          path: jvm/library/src/main/resources/
      - name: 🚀 Publish JVM library to Maven Local
        run: jvm/gradlew --project-dir jvm/ publishToMavenLocal
      - name: 📤 Upload JVM JAR
        if: matrix.java == '21'
        uses: actions/upload-artifact@v4
        with:
          name: jvm-jar
          path: ~/.m2/repository/io/tira/tirex-tracker/*/tirex-tracker-*.jar
      - name: 🚀 Publish JVM library to GitHub Packages
        if: matrix.java == '21'
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: jvm/gradlew --project-dir jvm/ publishAllPublicationsToGitHubPackagesRepository
  python-build:
    name: 🏗️ Build Python wheels
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    needs:
      - c-build-library
      - c-check-format
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: 📥 Download Linux library
        uses: actions/download-artifact@v4
        with:
          name: c-library-linux
          path: python/tirex_tracker/
      - name: 📥 Download macOS library
        uses: actions/download-artifact@v4
        with:
          name: c-library-macos
          path: python/tirex_tracker/
      - name: 📥 Download Windows library
        uses: actions/download-artifact@v4
        with:
          name: c-library-windows
          path: python/tirex_tracker/
      - name: 🧰 Install dependencies
        run: pip install build twine
      - name: 🏗️ Build Python wheels
        run: python -m build python
      - name: 🧪 Check package bundles
        run: twine check python/dist/*
      - name: 📤 Upload Python wheels
        if: matrix.python == '3.13'
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels
          path: python/dist/
  python-check:
    name: 🔍 Check Python code
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    needs:
      - c-build-library
      - c-check-format
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: python/pyproject.toml
      - name: 📥 Download Linux library
        uses: actions/download-artifact@v4
        with:
          name: c-library-linux
          path: python/tirex_tracker/
      - name: 📥 Download macOS library
        uses: actions/download-artifact@v4
        with:
          name: c-library-macos
          path: python/tirex_tracker/
      - name: 📥 Download Windows library
        uses: actions/download-artifact@v4
        with:
          name: c-library-windows
          path: python/tirex_tracker/
      - name: 🧰 Install dependencies
        run: pip install -e python[tests]
      - name: 🔍 Check Python code
        run: ruff check python
  python-typing:
    name: 🔍 Check Python static typing
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    needs:
      - c-build-library
      - c-check-format
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: python/pyproject.toml
      - name: 📥 Download Linux library
        uses: actions/download-artifact@v4
        with:
          name: c-library-linux
          path: python/tirex_tracker/
      - name: 📥 Download macOS library
        uses: actions/download-artifact@v4
        with:
          name: c-library-macos
          path: python/tirex_tracker/
      - name: 📥 Download Windows library
        uses: actions/download-artifact@v4
        with:
          name: c-library-windows
          path: python/tirex_tracker/
      - name: 🧰 Install dependencies
        run: pip install -e python[tests]
      - name: 🔍 Check Python static typing
        run: mypy python
  python-security:
    name: 🔍 Check Python code security
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    needs:
      - c-build-library
      - c-check-format
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: python/pyproject.toml
      - name: 📥 Download Linux library
        uses: actions/download-artifact@v4
        with:
          name: c-library-linux
          path: python/tirex_tracker/
      - name: 📥 Download macOS library
        uses: actions/download-artifact@v4
        with:
          name: c-library-macos
          path: python/tirex_tracker/
      - name: 📥 Download Windows library
        uses: actions/download-artifact@v4
        with:
          name: c-library-windows
          path: python/tirex_tracker/
      - name: 🧰 Install dependencies
        run: pip install -e python[tests]
      - name: 🔍 Check Python code security
        run: bandit -c python/pyproject.toml -r python
  python-test:
    name: 🧪 Test Python code
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    needs:
      - c-build-library
      - c-check-format
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 🧰 Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: python/pyproject.toml
      - name: 📥 Download Linux library
        uses: actions/download-artifact@v4
        with:
          name: c-library-linux
          path: python/tirex_tracker/
      - name: 📥 Download macOS library
        uses: actions/download-artifact@v4
        with:
          name: c-library-macos
          path: python/tirex_tracker/
      - name: 📥 Download Windows library
        uses: actions/download-artifact@v4
        with:
          name: c-library-windows
          path: python/tirex_tracker/
      - name: 🧰 Install dependencies
        run: pip install -e python[tests]
      - name: 🧪 Test Python code
        run: pytest --cov --cov-report xml python
      - name: 📤 Upload coverage to Codecov
        if: matrix.python == '3.13'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
  python-publish:
    name: 🚀 Publish Python wheels to PyPI
    if: github.event_name == 'push' && endsWith(github.event.base_ref, 'master') && startsWith(github.ref, 'refs/tags')
    needs:
      - c-build-library
      - c-check-format
      - python-build
      - python-check
      - python-typing
      - python-security
      - python-test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 📥 Download Python wheels
        uses: actions/download-artifact@v4
        with:
          name: python-wheels
          path: dist
      - name: 🚀 Publish Python wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  github-release:
    name: 🚀 Create GitHub release
    if: github.event_name == 'push' && endsWith(github.event.base_ref, 'master') && startsWith(github.ref, 'refs/tags')
    needs:
      - c-build-library
      - c-check-format
      - c-build-cli
      - c-build-debian-package
      - jvm-build
      - jvm-test
      - python-build
      - python-check
      - python-typing
      - python-security
      - python-test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v4
      - name: 📥 Download Linux library
        uses: actions/download-artifact@v4
        with:
          name: c-library-linux
          path: tmp/c/
      - name: 📥 Download macOS library
        uses: actions/download-artifact@v4
        with:
          name: c-library-macos
          path: tmp/c/
      - name: 📥 Download Windows library
        uses: actions/download-artifact@v4
        with:
          name: c-library-windows
          path: tmp/c/
      - name: 📥 Download Linux CLI
        uses: actions/download-artifact@v4
        with:
          name: c-cli-linux
          path: tmp/c/
      - name: ✏️ Rename Linux CLI
        run: mv tmp/c/measure tmp/c/measure-${{ github.ref_name }}-linux
      - name: 📥 Download macOS CLI
        uses: actions/download-artifact@v4
        with:
          name: c-cli-macos
          path: tmp/c/
      - name: ✏️ Rename macOS CLI
        run: mv tmp/c/measure tmp/c/measure-${{ github.ref_name }}-macos
      - name: 📥 Download Windows CLI
        uses: actions/download-artifact@v4
        with:
          name: c-cli-windows
          path: tmp/c/
      - name: ✏️ Rename Windows CLI
        run: mv tmp/c/measure.exe tmp/c/measure-${{ github.ref_name }}-windows.exe
      - name: 📥 Download Debian package
        uses: actions/download-artifact@v4
        with:
          name: c-debian-package
          path: tmp/c/
      - name: 📥 Download Python wheels
        uses: actions/download-artifact@v4
        with:
          name: python-wheels
          path: tmp/python/dist/
      - name: 📥 Download JVM JAR
        uses: actions/download-artifact@v4
        with:
          name: jvm-jar
          path: tmp/jvm/
      - name: 🚀 Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: |
            tmp/c/*.so
            tmp/c/*.dylib
            tmp/c/*.dll
            tmp/c/measure-*-linux
            tmp/c/measure-*-macos
            tmp/c/measure-*-windows.exe
            tmp/c/tirex-tracker-*-Linux.deb
            tmp/python/dist/*
            tmp/jvm/*/*.jar
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
          generate_release_notes: true
