name: Publish Docker image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  debian-package:
    name: Build Debian Package
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get -y install g++-13
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-13 -D CMAKE_CXX_COMPILER=g++-13 -DBUILD_SHARED_LIBS=NO -DMEASURECMD_BUILD_DOCS=NO -DMEASURECMD_BUILD_DEB=YES
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release --target package
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{github.workspace}}/build/measure-0.0.1rc-Linux.deb
  linux-binary:
    name: Build Linux Binary
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get -y install g++-13
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-13 -D CMAKE_CXX_COMPILER=g++-13 -DBUILD_SHARED_LIBS=NO -DMEASURECMD_BUILD_DOCS=NO -DMEASURECMD_BUILD_DEB=NO
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release --target measurecmd
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{github.workspace}}/build/src/measurecmd
